Tasks

Find total marks of every student.
Find average marks.
Highest scorer.
Lowest scorer.
Average marks of each subject.
Students scoring above 80 average.
Replace marks below 60 with 60 (grace marks).
Add a fourth subject.

In [1]:
import numpy as np

In [55]:
marks = np.array([
    [78, 82, 91],
    [56, 61, 70],
    [90, 88, 95],
    [57, 56, 65],
    [85, 90, 89]
])

In [25]:
total=np.sum(marks[:,:],axis=1)

In [26]:
total

array([251, 187, 273, 204, 264])

In [ ]:
# Find average marks.

In [ ]:
average=np.mean(marks[:,:],axis=1)

In [24]:
average

array([83.66666667, 62.33333333, 91.        , 68.        , 88.        ])

higestscorer

In [27]:
high_scorer=total.max()

In [28]:
high_scorer

np.int64(273)

In [29]:
low_score=total.min()

In [30]:
low_score

np.int64(187)

In [ ]:
# marks.mean()
#overall avg marks

np.float64(78.6)

In [32]:
# Students scoring above 80 average.
for i in average:
    if i > 80:
        print(i)

83.66666666666667
91.0
88.0


Replace marks below 60 with 60 (grace marks).

In [33]:
marks

array([[78, 82, 91],
       [56, 61, 70],
       [90, 88, 95],
       [67, 72, 65],
       [85, 90, 89]])

In [57]:
# marks=marks[ marks<60 ]=60
# marks

marks[:,:][marks[:,:] <60]=60


In [61]:
marks #i have reassighned value here for grace marks , so above result may vary if you run all the cell combine .... 

array([[78, 82, 91],
       [60, 61, 70],
       [90, 88, 95],
       [60, 60, 65],
       [85, 90, 89]])

In [62]:
# fourth subject we have to add there 
fourthsub=np.array([87,54,76,87,90])

In [71]:
updated=np.column_stack((marks,fourthsub))
marks=updated

In [72]:
marks

array([[78, 82, 91, 87],
       [60, 61, 70, 54],
       [90, 88, 95, 76],
       [60, 60, 65, 87],
       [85, 90, 89, 90]])