Average temperature
Hottest day
Coldest day
Days above 35°C
Count rainy season days (<32)
Convert Celsius to Fahrenheit
Difference between consecutive days

In [4]:
import numpy as np

In [11]:
temp = np.array([31,33,35,36,39,41,42,40,38,36,34,33,32,30])

In [3]:

for i in  range (len(temp)):
    print(f"{i+1} : {temp[i]}") 

1 : 31
2 : 33
3 : 35
4 : 36
5 : 39
6 : 41
7 : 42
8 : 40
9 : 38
10 : 36
11 : 34
12 : 33
13 : 32
14 : 30


<!-- FINDING 14 DAYS AVERAG TEMPERATURE  -->

In [4]:
temp.mean()

np.float64(35.714285714285715)

In [5]:
# Hottest day
# and which day occured 

In [6]:
temp.max()

np.int64(42)

In [7]:
temp.argmax()

np.int64(6)

<!-- COLDEST DAY  AND COLDEST TEMP THAT DAY   -->

In [8]:
mini=temp.min()

In [9]:
day=temp.argmin() +1

In [10]:
print(f"the coldest day is {day} with {mini} Celsius")

the coldest day is 14 with 30 Celsius


In [11]:
# Days above 35°C

In [12]:
days = np.where(temp >35)[0] +1
for day in days :
    print(f" {temp[day-1]} on {day}th day")

 36 on 4th day
 39 on 5th day
 41 on 6th day
 42 on 7th day
 40 on 8th day
 38 on 9th day
 36 on 10th day


In [13]:
cool=np.where(temp<32)[0]+1
for cools in cool:
    print(f"day :{cools} and {temp[cools-1] } degre C")

day :1 and 31 degre C
day :14 and 30 degre C


In [14]:
# F = (C × 9/5) + 32

# for i in temp:
#     print(f"{i* (9/5) +32}")
fahrenhite= temp * 9/5 +32
print(fahrenhite)

[ 87.8  91.4  95.   96.8 102.2 105.8 107.6 104.  100.4  96.8  93.2  91.4
  89.6  86. ]


<!-- temp difference  -->

In [15]:
temp

array([31, 33, 35, 36, 39, 41, 42, 40, 38, 36, 34, 33, 32, 30])

In [16]:
change =np.diff(temp)
for i,c in enumerate(change,start=1):
    print(f"from day {i} to {i+1}  : {c:+}")

from day 1 to 2  : +2
from day 2 to 3  : +2
from day 3 to 4  : +1
from day 4 to 5  : +3
from day 5 to 6  : +2
from day 6 to 7  : +1
from day 7 to 8  : -2
from day 8 to 9  : -2
from day 9 to 10  : -2
from day 10 to 11  : -2
from day 11 to 12  : -1
from day 12 to 13  : -1
from day 13 to 14  : -2


In [6]:
# Increase every temperature by 1.5°C to simulate a forecast.
temp

array([31, 33, 35, 36, 39, 41, 42, 40, 38, 36, 34, 33, 32, 30])

In [19]:
forecast=temp + 1.5
forecast

array([32.5, 34.5, 36.5, 37.5, 40.5, 42.5, 43.5, 41.5, 39.5, 37.5, 35.5,
       34.5, 33.5, 31.5])

In [ ]:
# Replace every temperature above 40°C with 40°C (simulating a sensor that cannot record values above 40°C).

temp[temp>40]=40
temp



array([31, 33, 35, 36, 39, 40, 40, 40, 38, 36, 34, 33, 32, 30])

In [ ]:
# another way
temp=np.where(temp>30,30,temp)
temp

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30])

Find all days where the temperature was between 33°C and 38°C (inclusive).

In [22]:
temp

array([31, 33, 35, 36, 39, 41, 42, 40, 38, 36, 34, 33, 32, 30])

In [17]:
days=np.where((temp>=33) & (temp<=38))[0]
for i in days:
    print(f"Day {i+1} : {temp[i]} *C ")

Day 2 : 33 *C 
Day 3 : 35 *C 
Day 4 : 36 *C 
Day 9 : 38 *C 
Day 10 : 36 *C 
Day 11 : 34 *C 
Day 12 : 33 *C 


In [25]:
condition=[
    temp<32,
    (temp>=32) &(temp<=37),
    temp>37
]
choices=["cold","normal","hot"]
weather=np.select(condition,choices,default="unknown")
print(weather)

['cold' 'normal' 'normal' 'normal' 'hot' 'hot' 'hot' 'hot' 'hot' 'normal'
 'normal' 'normal' 'normal' 'cold']


In [ ]:
for i , d in enumerate(temp,start=1):
    if d <=32:
        status="cool"
    elif d <= 38 :
        status="normal"
    elif d > 38:
        status="hot"
    print(f"day {i} : {d} - {status}")

day 1 : 31 - cool
day 2 : 33 - normal
day 3 : 35 - normal
day 4 : 36 - normal
day 5 : 39 - hot
day 6 : 41 - hot
day 7 : 42 - hot
day 8 : 40 - hot
day 9 : 38 - normal
day 10 : 36 - normal
day 11 : 34 - normal
day 12 : 33 - normal
day 13 : 32 - cool
day 14 : 30 - cool


In [32]:
temp


array([31, 33, 35, 36, 39, 41, 42, 40, 38, 36, 34, 33, 32, 30])